### ISSUE TITLE
package.json type commonjs -> module?

### ISSUE THREAD

**Issue by zantiu** [twickstrom/vue-dropzone#5]
In package.json: should "type": "commonjs" not rather be "type": "module"?
Because if commonjs then it cannot be imported with 'import'.

**Comment by vipvimal04** [comment]
We are facing the same issue. it's working fine if I changed the type as module or empty(""). Can you update the same in package.json?

**Comment by beInDev** [comment]
Same here

**Comment by sukh-idgateway** [comment]
I've created a fork and published a new version of the package here: https://www.npmjs.com/package/dropzone-vue3

**Comment by cristiannietodev91** [comment]
The @sukh-idgateway forked version works in vue3 for me. It helped me to solve the issue `import' and 'export' may appear only with 'sourceType: module`. 

@twickstrom can you accept guys sending PRs as maintainers this is a super helpful library that needs to be supported in vue3.

**Comment by twickstrom** [comment]
> The @sukh-idgateway forked version works in vue3 for me. It helped me to solve the issue `import' and 'export' may appear only with 'sourceType: module`.
> 
> @twickstrom can you accept guys sending PRs as maintainers this is a super helpful library that needs to be supported in vue3.

I’ll try to do a better job keeping an eye out for PR’s

**Comment by uccmen** [comment]
is it possible that you merged the PR but did not publish to NPM ? @twickstrom 
looks like folks are still seeing the error

```
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import 'dropzone/dist/dropzone.css'
| import vueDropzone from './components/vue-dropzone.vue'
```
